# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI-s.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(340, 100)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(10, 20, 80, 40))
        self.StartButton.setObjectName("StartButton")
        self.StopButton = QtWidgets.QPushButton(self.centralwidget)
        self.StopButton.setGeometry(QtCore.QRect(100, 20, 80, 40))
        self.StopButton.setObjectName("StopButton")
        self.SettingButton = QtWidgets.QPushButton(self.centralwidget)
        self.SettingButton.setGeometry(QtCore.QRect(190, 20, 60, 40))
        self.SettingButton.setObjectName("SettingButton")
        self.AboutButton = QtWidgets.QPushButton(self.centralwidget)
        self.AboutButton.setGeometry(QtCore.QRect(260, 20, 60, 40))
        self.AboutButton.setObjectName("AboutButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.StatusBar = QtWidgets.QStatusBar(MainWindow)
        self.StatusBar.setObjectName("StatusBar")
        MainWindow.setStatusBar(self.StatusBar)
        self.SettingButton.clicked.connect(MainWindow.ShowSettingWindow)
        self.AboutButton.clicked.connect(MainWindow.About)
        self.StartButton.clicked.connect(MainWindow.StartTcpioneer)
        self.StopButton.clicked.connect(MainWindow.StopTcpioneer)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PixLCG"))
        self.StartButton.setText(_translate("MainWindow", "启动服务"))
        self.StopButton.setText(_translate("MainWindow", "停止服务"))
        self.SettingButton.setText(_translate("MainWindow", "设置"))
        self.AboutButton.setText(_translate("MainWindow", "关于"))
